{% set name = "python-manilaclient" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/9b/14/c4a07dd2ab6563b75a2837e54dbf76536917891f06c975c78d83cd13dedd/python_manilaclient-{{ version }}.tar.gz
  sha256: 5322a7e03c7b1a94471ca6d61e64302681a9edb3af954a51a73420f337a460e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pbr >=2.0.0
    - setuptools
  run:
    - python >={{ python_min }}
    - pbr !=2.1.0,>=2.0.0
    - oslo.config >=5.2.0
    - oslo.log >=3.36.0
    - oslo.serialization !=2.19.1,>=2.18.0
    - oslo.utils >=3.33.0
    - prettytable >=0.7.1
    - requests >=2.14.2
    - simplejson >=3.5.1
    - babel !=2.4.0,>=2.3.4
    - osc-lib >=1.10.0
    - python-keystoneclient >=3.8.0
    - debtcollector >=1.2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - manilaclient

about:
  home: https://docs.openstack.org/python-manilaclient/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Client library for OpenStack Manila API.
  doc_url: https://docs.openstack.org/python-manilaclient/latest/
  dev_url: https://opendev.org/openstack/python-manilaclient

extra:
  recipe-maintainers:
    - tschoonj
