{% set name = "python-manilaclient" %}
{% set version = "5.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/b9/09/ac69bbccdc7a144b6c4bac3bb6722f6bfefcb0bb4c24a8ba092c71cece76/python_manilaclient-{{ version }}.tar.gz
  sha256: 570f1e8b6d8c1265ceca0b703ad28b0c831c6f79c18ea38d811ae17d2185b897

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - manila = manilaclient.shell:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pbr >=2.0.0
    - setuptools
  run:
    - python >={{ python_min }}
    - pbr !=2.1.0,>=2.0.0
    - oslo.config >=5.2.0
    - oslo.log >=3.36.0
    - oslo.serialization !=2.19.1,>=2.18.0
    - oslo.utils >=3.33.0
    - prettytable >=0.7.1
    - requests >=2.14.2
    - simplejson >=3.5.1
    - babel !=2.4.0,>=2.3.4
    - osc-lib >=1.10.0
    - python-keystoneclient >=3.8.0
    - debtcollector >=1.2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - manilaclient
  commands:
    - manila -h

about:
  home: https://docs.openstack.org/python-manilaclient/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Client library for OpenStack Manila API.
  doc_url: https://docs.openstack.org/python-manilaclient/latest/
  dev_url: https://opendev.org/openstack/python-manilaclient

extra:
  recipe-maintainers:
    - tschoonj
